# ref: https://github.com/actions/virtual-environments
name: amd64 Linux

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        option: [
          '',
          '--repo_env=BAZEL_CXXOPTS="-std=c++17"',
          '--action_env=BAZEL_CXXOPTS="-std=c++17"',
          '--cxxopt="-std=c++17"']
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: |
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update
        sudo apt-get install bazel
    - name: Check bazel
      run:  bazel version
    - name: Build
      run: >
        bazel build
        -c opt
        ${{ matrix.option }}
        --subcommands=true
        ...
    - name: Test
      run: >
        bazel test
        -c opt
        ${{ matrix.option }}
        --test_output=all
        ...
