# ref: https://github.com/actions/runner-images
name: amd64 macOS Bazel

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        option: [
          '',
          '--repo_env=BAZEL_CXXOPTS="-std=c++17"',
          '--action_env=BAZEL_CXXOPTS="-std=c++17"',
          '--cxxopt="-std=c++17"']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Bazel
        run: |
          brew update
          brew unlink bazelisk
          brew install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          ${{ matrix.option }}
          --subcommands=true
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          ${{ matrix.option }}
          --test_output=all
          ...
