name: amd64 macOS

on: [push, pull_request]

jobs:
  bazel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: |
        brew update
        #brew install bazel
    - name: Check Bazel
      run: bazel version
    - name: Build
      run: bazel build -c opt --repo_env=BAZEL_CXXOPTS="-std=c++17" --subcommands=true ...
    - name: Test
      run: bazel test -c opt --repo_env=BAZEL_CXXOPTS="-std=c++17" --test_output=all ...
