# ref: https://github.com/actions/runner-images
name: arm64 MacOS Bazel

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    name: MacOS•Bazel
    runs-on: macos-latest # arm64 based macos runner
    steps:
      - uses: actions/checkout@v5
      - name: Show Bazel version
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          --enable_bzlmod
          //...
      - name: Test
        run: >
          bazel test
          -c opt
          --subcommands=pretty_print
          --enable_bzlmod
          //...

  arm64_macos_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
